<?xml version="1.0" encoding="UTF-8"?>
<!--
  HotelMountains.com — Rank Math style sitemap stylesheet.
  Renders sitemap_index.xml and child sitemaps (page-sitemap.xml,
  destination-sitemap.xml, post-sitemap.xml) as a clean HTML table
  when opened in a browser, just like the Rank Math SEO plugin.
-->
<xsl:stylesheet version="2.0"
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap — HotelMountains.com</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css">
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #333; max-width: 980px; margin: 30px auto; padding: 0 20px; }
          h1 { font-size: 22px; margin-bottom: 4px; }
          .intro { color: #666; font-size: 14px; margin-bottom: 20px; }
          a { color: #2563eb; text-decoration: none; }
          a:hover { text-decoration: underline; }
          table { width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 2px rgba(0,0,0,.06); }
          th, td { padding: 10px 14px; border-bottom: 1px solid #eee; font-size: 14px; text-align: left; }
          th { background: #f3f4f6; font-weight: 600; }
          tr:nth-child(even) td { background: #fafafa; }
          .count { color: #888; font-size: 13px; margin-bottom: 8px; }
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        <p class="intro">
          Generated by HotelMountains.com — Rank Math compatible format.
          This sitemap is intended for search engines like Google and Bing.
        </p>

        <xsl:if test="sitemap:sitemapindex">
          <p class="count">
            Number of sitemaps: <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/>
          </p>
          <table>
            <tr><th>Sitemap</th><th>Last Modified</th></tr>
            <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
              <tr>
                <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                <td><xsl:value-of select="sitemap:lastmod"/></td>
              </tr>
            </xsl:for-each>
          </table>
        </xsl:if>

        <xsl:if test="sitemap:urlset">
          <p class="count">
            Number of URLs: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
          </p>
          <table>
            <tr><th>URL</th><th>Images</th><th>Last Modified</th></tr>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                <td><xsl:value-of select="count(image:image)"/></td>
                <td><xsl:value-of select="sitemap:lastmod"/></td>
              </tr>
            </xsl:for-each>
          </table>
        </xsl:if>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
