<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap — HotelMountains.com</title>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <meta name="robots" content="noindex,follow"/>
        <style type="text/css">
          :root{
            --bg:#f7f8fa;
            --card:#ffffff;
            --text:#1f2937;
            --muted:#6b7280;
            --primary:#0d7d6c;
            --accent:#f97316;
            --border:#e5e7eb;
          }
          *{box-sizing:border-box}
          body{margin:0;padding:0;font:14px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:var(--bg);color:var(--text)}
          .wrap{max-width:1080px;margin:0 auto;padding:32px 20px 60px}
          .header{background:linear-gradient(135deg,var(--primary),#0a5f53);color:#fff;border-radius:14px;padding:28px 30px;margin-bottom:22px;box-shadow:0 6px 24px -8px rgba(13,125,108,.45)}
          .header h1{margin:0 0 6px;font-size:22px;font-weight:700;letter-spacing:-.01em}
          .header p{margin:0;opacity:.92;font-size:13px}
          .header strong{color:#fff}
          .meta{display:flex;flex-wrap:wrap;gap:18px;margin:14px 0 0;font-size:12.5px;opacity:.95}
          .meta span{background:rgba(255,255,255,.14);padding:5px 11px;border-radius:999px;backdrop-filter:blur(4px)}
          .card{background:var(--card);border:1px solid var(--border);border-radius:14px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.04)}
          table{width:100%;border-collapse:collapse;font-size:13.5px}
          thead th{background:#f3f4f6;text-align:left;padding:12px 16px;font-weight:600;color:var(--muted);text-transform:uppercase;font-size:11.5px;letter-spacing:.04em;border-bottom:1px solid var(--border)}
          tbody td{padding:12px 16px;border-bottom:1px solid var(--border);vertical-align:middle}
          tbody tr:last-child td{border-bottom:none}
          tbody tr:hover{background:#fafbfc}
          a{color:var(--primary);text-decoration:none;word-break:break-all}
          a:hover{color:var(--accent);text-decoration:underline}
          .num{color:var(--muted);width:54px}
          .pill{display:inline-block;padding:3px 9px;border-radius:999px;font-size:11px;font-weight:600;background:#ecfdf5;color:#047857}
          .pill.gray{background:#f3f4f6;color:#4b5563}
          .footer{margin-top:18px;text-align:center;color:var(--muted);font-size:12px}
          .footer a{color:var(--muted);text-decoration:underline}
          @media (max-width:640px){
            .header{padding:22px}
            .header h1{font-size:18px}
            thead th,tbody td{padding:10px 12px;font-size:12.5px}
          }
        </style>
      </head>
      <body>
        <div class="wrap">
          <div class="header">
            <h1>XML Sitemap</h1>
            <xsl:choose>
              <xsl:when test="sitemap:sitemapindex">
                <p>Generated by <strong>HotelMountains.com SEO</strong> — this is the master sitemap index. It lists every section sitemap so search engines can crawl the site efficiently.</p>
                <div class="meta">
                  <span>Type: <strong>Sitemap Index</strong></span>
                  <span>Sitemaps: <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong></span>
                </div>
              </xsl:when>
              <xsl:otherwise>
                <p>Generated by <strong>HotelMountains.com SEO</strong> — this URL set lists all crawlable pages in this section together with last-modified dates and update frequency.</p>
                <div class="meta">
                  <span>Type: <strong>URL Set</strong></span>
                  <span>URLs: <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong></span>
                </div>
              </xsl:otherwise>
            </xsl:choose>
          </div>

          <xsl:choose>
            <!-- ============== SITEMAP INDEX ============== -->
            <xsl:when test="sitemap:sitemapindex">
              <div class="card">
                <table>
                  <thead>
                    <tr>
                      <th class="num">#</th>
                      <th>Sitemap URL</th>
                      <th>Last Modified</th>
                    </tr>
                  </thead>
                  <tbody>
                    <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                      <tr>
                        <td class="num"><xsl:value-of select="position()"/></td>
                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                        <td><xsl:value-of select="sitemap:lastmod"/></td>
                      </tr>
                    </xsl:for-each>
                  </tbody>
                </table>
              </div>
            </xsl:when>

            <!-- ============== URL SET ============== -->
            <xsl:otherwise>
              <div class="card">
                <table>
                  <thead>
                    <tr>
                      <th class="num">#</th>
                      <th>URL</th>
                      <th>Images</th>
                      <th>Priority</th>
                      <th>Change Freq.</th>
                      <th>Last Mod.</th>
                    </tr>
                  </thead>
                  <tbody>
                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                      <tr>
                        <td class="num"><xsl:value-of select="position()"/></td>
                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                        <td>
                          <xsl:choose>
                            <xsl:when test="image:image">
                              <span class="pill"><xsl:value-of select="count(image:image)"/></span>
                            </xsl:when>
                            <xsl:otherwise><span class="pill gray">0</span></xsl:otherwise>
                          </xsl:choose>
                        </td>
                        <td><xsl:value-of select="sitemap:priority"/></td>
                        <td><xsl:value-of select="sitemap:changefreq"/></td>
                        <td><xsl:value-of select="sitemap:lastmod"/></td>
                      </tr>
                    </xsl:for-each>
                  </tbody>
                </table>
              </div>
            </xsl:otherwise>
          </xsl:choose>

          <p class="footer">
            This XML Sitemap is built for search engines like Google &amp; Bing.<br/>
            Visit <a href="https://hotelmountains.com">HotelMountains.com</a> for mountain travel guides &amp; tours.
          </p>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
