/**
 * Sitemap generator — Rank Math SEO compatible.
 *
 * Mirrors the exact format produced by the Rank Math WordPress plugin:
 *   - sitemap_index.xml lists child sitemaps with full ISO 8601 lastmod
 *   - Per-sitemap files use <urlset> with image:image children only
 *     (NO <changefreq>, NO <priority> — Rank Math omits both by design)
 *   - xml-stylesheet href is protocol-relative (//site/main-sitemap.xsl)
 *   - Tab indentation, exactly like Rank Math output
 *
 * Reads:
 *   - src/data/destinations.ts
 *   - src/data/blogArticles.ts
 *
 * Writes:
 *   - public/sitemap_index.xml
 *   - public/page-sitemap.xml
 *   - public/destination-sitemap.xml
 *   - public/post-sitemap.xml
 *
 * Usage:  node scripts/generate-sitemap.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const PUBLIC_DIR = resolve(ROOT, "public");
const SITE = "https://hotelmountains.com";
const SITE_HOST = "hotelmountains.com";

/** Rank Math uses full ISO 8601 timestamps with timezone, e.g. 2026-04-22T10:15:00+00:00 */
const NOW_ISO = new Date().toISOString().replace(/\.\d{3}Z$/, "+00:00");
const dateToIso = (yyyyMmDd) =>
  yyyyMmDd && /^\d{4}-\d{2}-\d{2}$/.test(yyyyMmDd)
    ? `${yyyyMmDd}T00:00:00+00:00`
    : NOW_ISO;

/** Rank Math uses a protocol-relative stylesheet path. */
const STYLESHEET = `//${SITE_HOST}/main-sitemap.xsl`;

mkdirSync(PUBLIC_DIR, { recursive: true });

/* -------------------- tiny extractors (no TS compile) -------------------- */

function readSource(rel) {
  return readFileSync(resolve(ROOT, rel), "utf8");
}

/** Extract per-entry fields from each top-level object literal in an exported array. */
function extractEntries(source, fields) {
  const entries = [];
  const blockRegex = /\{\s*slug:\s*"([^"]+)"[\s\S]*?(?=\n\s*\},?\s*\n\s*\{|\n\s*\}\s*\];)/g;
  let m;
  while ((m = blockRegex.exec(source)) !== null) {
    const block = m[0];
    const slug = m[1];
    const out = { slug };
    for (const f of fields) {
      const re = new RegExp(`${f}:\\s*"([^"]+)"`);
      const fm = block.match(re);
      if (fm) out[f] = fm[1];
    }
    entries.push(out);
  }
  return entries;
}

const destSource = readSource("src/data/destinations.ts");
const blogSource = readSource("src/data/blogArticles.ts");

const destinations = extractEntries(destSource, ["heroImage", "name"]).map((d) => ({
  slug: d.slug,
  image: d.heroImage,
  name: d.name || d.slug.replace(/-/g, " "),
}));

const posts = extractEntries(blogSource, ["image", "date", "title"]).map((p) => ({
  slug: p.slug,
  image: p.image,
  date: p.date,
  title: p.title || "",
}));

if (!destinations.length) throw new Error("No destinations parsed");
if (!posts.length) throw new Error("No blog posts parsed");

/* -------------------- builders -------------------- */

const xmlHead = `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="${STYLESHEET}"?>`;

const escapeXml = (s) =>
  String(s).replace(/[<>&'"]/g, (c) =>
    ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" }[c])
  );

/**
 * Render a single <url> block in Rank Math style.
 * - No changefreq / priority (Rank Math omits these intentionally)
 * - One <image:image><image:loc> per image
 */
function urlEntry({ loc, lastmod, images = [] }) {
  const imageBlocks = images
    .filter(Boolean)
    .map(
      (img) => `\t\t<image:image>
\t\t\t<image:loc>${escapeXml(img)}</image:loc>
\t\t</image:image>`
    )
    .join("\n");

  return `\t<url>
\t\t<loc>${escapeXml(loc)}</loc>
\t\t<lastmod>${lastmod}</lastmod>${imageBlocks ? `\n${imageBlocks}` : ""}
\t</url>`;
}

function urlset(entries) {
  return `${xmlHead}
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd
                            http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd">
${entries.map(urlEntry).join("\n")}
</urlset>
<!-- XML Sitemap generated by HotelMountains.com (Rank Math compatible format) -->
`;
}

/* -------------------- page-sitemap.xml -------------------- */
/**
 * All static + landing pages on the site. Add new pages here so they
 * automatically appear in the next regeneration.
 */
const pages = [
  { path: "/" },
  { path: "/blog" },
  { path: "/about" },
  { path: "/contact" },
  { path: "/mountain-hotels" },
  { path: "/hiking-tours" },
  { path: "/ski-trips" },
  { path: "/privacy-policy" },
  { path: "/terms-of-service" },
  { path: "/cookie-policy" },
  { path: "/dmca" },
  { path: "/legal-notice" },
  { path: "/parents-info" },
];

const pageXml = urlset(
  pages.map((p) => ({
    loc: `${SITE}${p.path}`,
    lastmod: NOW_ISO,
  }))
);

/* -------------------- destination-sitemap.xml -------------------- */

const destXml = urlset(
  destinations.map((d) => ({
    loc: `${SITE}/destination/${d.slug}`,
    lastmod: NOW_ISO,
    images: [d.image],
  }))
);

/* -------------------- post-sitemap.xml -------------------- */

const postXml = urlset(
  posts.map((p) => ({
    loc: `${SITE}/blog/${p.slug}`,
    lastmod: dateToIso(p.date),
    images: [p.image],
  }))
);

/* -------------------- sitemap.xml (flat, all routes) -------------------- */
/**
 * Single combined sitemap that mirrors EVERY route declared in
 * src/App.tsx (static pages + /destination/:slug + /blog/:slug).
 * Useful for tools that don't follow sitemap indexes.
 */
const allEntries = [
  ...pages.map((p) => ({ loc: `${SITE}${p.path}`, lastmod: NOW_ISO })),
  ...destinations.map((d) => ({
    loc: `${SITE}/destination/${d.slug}`,
    lastmod: NOW_ISO,
    images: [d.image],
  })),
  ...posts.map((p) => ({
    loc: `${SITE}/blog/${p.slug}`,
    lastmod: dateToIso(p.date),
    images: [p.image],
  })),
];
const flatXml = urlset(allEntries);

/* -------------------- sitemap_index.xml -------------------- */
/**
 * Rank Math sitemap_index lists child sitemaps with their own lastmod.
 * We use the most recent entry of each child as its lastmod.
 */
const sitemapIndex = `${xmlHead}
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
\t<sitemap>
\t\t<loc>${SITE}/page-sitemap.xml</loc>
\t\t<lastmod>${NOW_ISO}</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>${SITE}/destination-sitemap.xml</loc>
\t\t<lastmod>${NOW_ISO}</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>${SITE}/post-sitemap.xml</loc>
\t\t<lastmod>${dateToIso(
  posts.map((p) => p.date).filter(Boolean).sort().reverse()[0]
)}</lastmod>
\t</sitemap>
</sitemapindex>
<!-- XML Sitemap Index generated by HotelMountains.com (Rank Math compatible format) -->
`;

/* -------------------- write -------------------- */

const outputs = [
  ["sitemap.xml", flatXml],
  ["sitemap_index.xml", sitemapIndex],
  ["page-sitemap.xml", pageXml],
  ["destination-sitemap.xml", destXml],
  ["post-sitemap.xml", postXml],
];

for (const [name, body] of outputs) {
  writeFileSync(resolve(PUBLIC_DIR, name), body, "utf8");
  console.log(`✓ wrote public/${name}`);
}

console.log(
  `\nPages: ${pages.length} | Destinations: ${destinations.length} | Posts: ${posts.length}`
);
